# Generated by Django 4.2.16 on 2025-01-30 16:30

from django.db import migrations
import saleor.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0196_slug_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background_image',
            field=saleor.core.db.fields.LongNameImageField(blank=True, max_length=500, null=True, upload_to='category-backgrounds'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='background_image',
            field=saleor.core.db.fields.LongNameImageField(blank=True, max_length=500, null=True, upload_to='collection-backgrounds'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=saleor.core.db.fields.LongNameImageField(blank=True, max_length=500, null=True, upload_to='products'),
        ),
    ]
