# Generated by Django 4.2.16 on 2025-01-30 16:30

from django.db import migrations
import saleor.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_app_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='brand_logo_default',
            field=saleor.core.db.fields.LongNameImageField(blank=True, max_length=500, null=True, upload_to='app-brand-data'),
        ),
        migrations.AlterField(
            model_name='appinstallation',
            name='brand_logo_default',
            field=saleor.core.db.fields.LongNameImageField(blank=True, max_length=500, null=True, upload_to='app-installation-brand-data'),
        ),
    ]
