# Generated by Django 4.2.16 on 2025-01-30 16:30

from django.db import migrations
import saleor.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_auto_20240805_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=saleor.core.db.fields.LongNameImageField(blank=True, max_length=500, null=True, upload_to='user-avatars'),
        ),
    ]
